const allData = [
    {
        id: 21,
        name: "Dal",
        info: "Arhar Dal",
        image: "https://5.imimg.com/data5/OW/AT/MY-8481118/arhar-dal.jpg",
        price: "61/kg",
    },
    {
        id: 25,
        name: "Oil",
        info: "Saffola Gold Refined Oil",
        image: "https://m.media-amazon.com/images/I/61ZSTmboXVL._AC_UF1000,1000_QL80_.jpg",
        price: "170/litre",
    },
    {
        id: 27,
        name: "Spices",
        info: "Coriander Powder",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRmZNq1WziKph4nNFOXozSs0q3fnM5zL6PizmkH859yt905PcpUevh7ypuXzHhMJFjuzkKe0CnXIqOTtF_C3AqR7wDqXlKr0_sLk25Udi8PAWxiQ4iFwNtaww",
        price: "150/kg",
    },
    
    
    {
        id: 30,
        name: "Flour",
        info: "Maida",
        image: "https://www.pmarkproducts.com/wp-content/uploads/2019/04/back-1.png",
        price: "40/kg",
    },
    {
        id: 31,
        name: "Flour",
        info: "Besan (Gram Flour)",
        image: "https://m.media-amazon.com/images/I/61zW4mNhZbL.jpg",
        price: "60/kg",
    },
    {
        id: 32,
        name: "Snacks",
        info: "Potato Chips",
        image: "https://m.media-amazon.com/images/I/61zW4mNhZbL.jpg",
        price: "40/pack",
    },
    {
        id: 33,
        name: "Snacks",
        info: "Nachos",
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQAAA3gySbSXx6IvEBYE_dk5mnrJj56zkEwiMu0oo3XPZ8GzhqAxsy0phzqYJViZVpOvM5a19z9zCRevEIUb7Y_lhqHd7RqjCCOEM7Uk6A_Rb7MB_ZV8hvo3g",
        price: "40/pack",
    },
    {
        id: 34,
        name: "Biscuits",
        info: "Chocolate Cookies Dark Fantasy",
        image: "https://m.media-amazon.com/images/I/61Xph7Wux9L.jpg",
        price: "30/pack",
    },
    {
        id: 35,
        name: "Biscuits",
        info: "Britania Digestive Biscuits",
        image: "https://m.media-amazon.com/images/I/71+kVe5LuiL.jpg",
        price: "30/pack",
    },
    {
        id: 36,
        name: "Sauces",
        info: "Tomato Ketchup",
        image: "https://m.media-amazon.com/images/I/61pYfbia0aL.jpg",
        price: "80/bottle",
    },
    {
        id: 37,
        name: "Sauces",
        info: "Soy Sauce",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvr1E75cj9A49JM6dvttZw14cotCnhU3ntOA&s",
        price: "60/bottle",
    },
    {
        id: 22,
        name: "Dal",
        info: "Yellow Chana Dal",
        image: "https://5.imimg.com/data5/HS/QC/EC/SELLER-106270270/chana-dal.jpg",
        price: "85/kg",
    },
    
    {
        id: 26,
        name: "Spices",
        info: "Turmeric Powder",
        image: "https://m.media-amazon.com/images/I/61VsmZWfDbL.jpg",
        price: "200/kg",
    },
    {
        id: 23,
        name: "Dal",
        info: "Masoor Dal",
        image: "https://5.imimg.com/data5/PJ/GM/MY-36598921/masoor-malka-dal-500x500.jpg",
        price: "75/kg",
    },
    {
        id: 38,
        name: "Pasta",
        info: "Penne Pasta",
        image: "https://www.the-pasta-project.com/wp-content/uploads/Penne-Pasta-1.jpg",
        price: "80/kg",
    },
    {
        id: 39,
        name: "Noodles",
        info: "Instant Noodles",
        image: "https://masterchow.in/cdn/shop/files/Cup-noodles-Chowmien-_-Korean-2x.png?v=1719388578",
        price: "70/pack",
    },
    {
        id: 29,
        name: "Flour",
        info: "Whole Wheat Flour",
        image: "https://t4.ftcdn.net/jpg/01/20/00/55/360_F_120005524_K3y8Ku1CDDsDpQeZqFYgBksKmWDK0RcB.jpg",
        price: "45/kg",
    },
    {
        id: 1009,
        name: "Noodles",
        info: "Instant Noodles Maggie",
        image: "https://www.shutterstock.com/image-photo/chennai-india-april-12-2021-260nw-1959559120.jpg",
        price: "10/pack",
    },
    {
        id: 40,
        name: "Pickles",
        info: "Mango Pickle",
        image: "https://priyafoods.com/cdn/shop/products/MangoAvakayaWG300g.jpg?v=1689145579",
        price: "100/jar",
    },
    {
        id: 41,
        name: "Honey",
        info: "Organic Honey",
        image: "https://shivaorganic.com/cdn/shop/files/DSC_8233-1.jpg?v=1730006920&width=720",
        price: "450/bottle",
    },
    {
        id: 42,
        name: "Tea",
        info: "Green Tea",
        image: "https://goodricketea.in/cdn/shop/files/SymphonyGableTop100gPackof2.jpg?v=1704694151",
        price: "150/box",
    },
    {
        id: 24,
        name: "Dal",
        info: "Val Dal",
        image: "https://3.imimg.com/data3/UR/VP/MY-3704858/selection_003-500x500.png",
        price: "160/kg",
    },
    {
        id: 1010,
        name: "Tea",
        info: "Green Tea Taza",
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/tea/n/b/k/499-brooke-bond-combo-2-pouch-regular-tea-taaza-leaves-granules-original-imagthfzwhtt3nfd.jpeg?q=90&crop=false",
        price: "10/packet",
    },
    {
        id: 43,
        name: "Coffee",
        info: "Instant Coffee Powder",
        image: "https://sleepyowl.co/cdn/shop/files/jpg_1.jpg?v=1722620699",
        price: "400/box",
    },
    {
        id: 44,
        name: "Cereal",
        info: "Oats",
        image: "https://m.media-amazon.com/images/I/71d0wtpbxJL._AC_UF894,1000_QL80_.jpg",
        price: "180/kg",
    },
    {
        id: 45,
        name: "Cereal",
        info: "Cornflakes",
        image: "https://images-cdn.ubuy.co.in/668b588077d20426d24aa0b0-kellogg-s-corn-flakes-original-breakfast.jpg",
        price: "350/pack",
    },
    {
        id: 46,
        name: "Baking",
        info: "Baking Soda",
        image: "https://m.media-amazon.com/images/I/71YadUEzJSL._AC_UF894,1000_QL80_.jpg",
        price: "200/pack",
    },
    {
        id: 28,
        name: "Spices",
        info: "Red Chili Powder",
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSMciNUUnZOYc0vNl18Wa1EK01GpTs-rA3QKTS0yK4Gsh1lldLXRbK70YaEss0vA_jMx7P8QyMUGyjrVdZ4tKEPv_KqEZMwXTEtspi1-dlkZwtDpkfa__PgDg",
        price: "220/kg",
    },
    {
        id: 47,
        name: "Baking",
        info: "All-Purpose Flour",
        image: "https://rarefoodshop.com/cdn/shop/files/magnolia-all-purpose-flour-400g-36266157047988_600x600.png?v=1685693976",
        price: "50/kg",
    },
    {
        id: 48,
        name: "Dry Fruits",
        info: "Almonds",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcSht7O_Djlr7uZcAh-pdUIYzuBwTmzmHrng&s",
        price: "800/kg",
    },
    {
        id: 49,
        name: "Dry Fruits",
        info: "Cashew Nuts",
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/nut-dry-fruit/n/b/3/500-premium-whole-cashew-nuts-plain-100-crunchy-kaju-1-pouch-blk-original-imah3jr9gymu4ngk.jpeg?q=90&crop=false",
        price: "900/kg",
    },
    {
        id: 50,
        name: "Dry Fruits",
        info: "Raisins",
        image: "https://m.media-amazon.com/images/I/617wuLJioFL._AC_UF1000,1000_QL80_.jpg",
        price: "400/kg",
    },
    {
        id: 51,
        name: "Bread",
        info: "Whole Wheat Bread",
        image: "https://images.heb.com/is/image/HEBGrocery/001269327?fit=constrain,1&wid=800&hei=800&fmt=jpg&qlt=85,0&resMode=sharp2&op_usm=1.75,0.3,2,0",
        price: "40/loaf",
    },
    {
        id: 52,
        name: "Cheese",
        info: "Cheddar Cheese Block",
        image: "https://cremeitalia.com/cdn/shop/files/CheddarCheeseBlock_grande.png?v=1721385323",
        price: "250/500g",
    },
    {
        id: 53,
        name: "Butter",
        info: "Salted Butter",
        image: "https://theindiasupermart.com/cdn/shop/products/amul-salted-butter-dairy-malabar-500-g-225471.jpg?v=1665195070",
        price: "100/200g",
    },
    {
        id: 54,
        name: "Yogurt",
        info: "Greek Yogurt",
        image: "https://www.jiomart.com/images/product/original/494304016/mother-dairy-plan-greek-yoghurt-100-g-cup-product-images-o494304016-p610078936-0-202410071502.jpg?im=Resize=(420,420)",
        price: "80/pack",
    },
    {
        id: 55,
        name: "Milk",
        info: "Full Cream Milk",
        image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=900/app/assets/products/sliding_images/jpeg/8f6bfafc-ad44-422a-8e96-7e2d2994012a.jpg?ts=1707998856",
        price: "60/litre",
    },
    {
        id: 56,
        name: "Eggs",
        info: "Organic Brown Eggs",
        image: "https://5.imimg.com/data5/SELLER/Default/2021/1/PR/TJ/XG/99200938/bv380-jpg-500x500.jpg",
        price: "84/dozen",
    },
    {
        id: 57,
        name: "Chicken",
        info: "Fresh Chicken Breast",
        image: "https://www.debon.co.in/cdn/shop/products/CHICKENBREASTBONELESS-01_16ec7f41-753b-4a31-bca0-513ba563098d.jpg?v=1672122446",
        price: "200/kg",
    },
    {
        id: 58,
        name: "Fish",
        info: "Salmon Fillet",
        image: "https://d1z88p83zuviay.cloudfront.net/ProductVariantThumbnailImages/185ebcbd-893e-478a-b50f-9bc21458487d_425x425.jpg",
        price: "900/kg",
    },
    {
        id: 59,
        name: "Cereal",
        info: "Muesli with Dried Fruits",
        image: "https://m.media-amazon.com/images/I/71ECwJ72HrL.jpg",
        price: "330/pack",
    },
    {
        id: 60,
        name: "Vegetables",
        info: "Fresh Spinach",
        image: "https://m.media-amazon.com/images/I/71tdN2taTCL.jpg",
        price: "30/bundle",
    },
    {
        id: 61,
        name: "Vegetables",
        info: "Broccoli",
        image: "https://freshlee.in/cdn/shop/files/1000014_1080x.jpg?v=1706529099",
        price: "140/kg",
    },
    {
        id: 62,
        name: "Fruits",
        info: "Bananas",
        image: "https://www.orgpick.com/cdn/shop/products/banana-powder_large_f0d6750f-b412-4815-b1e1-7779bf18c354.jpg?v=1612510545",
        price: "60/dozen",
    },
    {
        id: 63,
        name: "Fruits",
        info: "Red Apples",
        image: "https://thumbs.dreamstime.com/b/apples-supermarket-apple-shelves-display-retail-store-organic-local-farmers-food-fruits-healthy-eating-fresh-supply-shopping-305087699.jpg",
        price: "180/kg",
    },
    {
        id: 64,
        name: "Fruits",
        info: "Watermelon",
        image: "https://kumaribasket.com/wp-content/uploads/2020/08/watermelon5.jpg",
        price: "30/kg",
    },
    {
        id: 65,
        name: "Coconut Water",
        info: "Fresh Coconut Water",
        image: "https://www.rusorganic.in/cdn/shop/files/Coconut_Fresh_Juice-coconut-water-cold-pressed-rus-organic-daily-subscription-juice.jpg?v=1722340730",
        price: "50/each",
    },
    {
        id: 66,
        name: "Juice",
        info: "Orange Juice",
        image: "https://www.rusorganic.in/cdn/shop/files/Fresh-orange-juice-cold-pressed-rus-organic-daily-delivery-juice-1litre-juice.jpg?v=1722340666",
        price: "120/litre",
    },
    {
        id: 67,
        name: "Jam",
        info: "Mixed Fruit Jam",
        image: "https://aachifoods.com/cdn/shop/files/Mixed-Fruit-Jam.webp?v=1727083254&width=1946",
        price: "180/jar",
    },
    {
        id: 68,
        name: "Chocolate",
        info: "Dark Chocolate",
        image: "https://freshlee.in/cdn/shop/files/1002303_d6a29892-665b-496d-a941-14b7876263b8_1080x.png?v=1726314729",
        price: "20/bar",
    },
    {
        id: 69,
        name: "Cocoa Powder",
        info: "Unsweetened Cocoa Powder",
        image: "https://d3kgrlupo77sg7.cloudfront.net/media/chococoorgspice.com/images/products/cocoa-powder-organic-coorg-cocoa-powder-500gm-pack.20200101191803.webp",
        price: "130/pack",
    },
    {
        id: 70,
        name: "Sugar Substitute",
        info: "Stevia Powder",
        image: "https://m.media-amazon.com/images/I/71SK3oxGaWL.jpg",
        price: "200/pack",
    },
    {
        id: 71,
        name: "Rice Cakes",
        info: "Plain Rice Cakes",
        image: "https://images-cdn.ubuy.co.in/634e33cb9174b567ca6f85c4-quaker-plain-unsalted-rice-cake-4-47.jpg",
        price: "80/pack",
    },
    {
        id: 72,
        name: "Popcorn",
        info: "Microwave Popcorn",
        image: "https://m.media-amazon.com/images/I/81-MtR+RcJL._AC_UF1000,1000_QL80_.jpg",
        price: "150/pack",
    },
    {
        id: 73,
        name: "Ice Cream",
        info: "Vanilla Ice Cream",
        image: "https://freshlee.in/cdn/shop/files/1038319_3f7ca3a7-88b7-4c2a-9452-d5b8ac9e2855_1080x.png?v=1726314815",
        price: "150/tub",
    },
    {
        id: 74,
        name: "Frozen Peas",
        info: "Frozen Green Peas",
        image: "https://www.smc-madhusudan.co.in/cdn/shop/files/FrozenPea1KGPOLLYPACK.jpg?v=1714552252&width=2048",
        price: "170/pack",
    },
    {
        id: 75,
        name: "Frozen Corn",
        info: "Sweet Corn",
        image: "https://freshlist.in/image/cache/catalog/001-product-images/00-Festival/Cadbury/frozen/frozen%20sweet%20corn%201kg-600x600.jpg",
        price: "100/pack",
    },
    {
        id: 76,
        name: "Frozen Veggie Mix",
        info: "Mixed Vegetables",
        image: "https://badshahchap.in/wp-content/uploads/2022/12/IMG-20230515-WA0026-1.jpg",
        price: "90/pack",
    },
    {
        id: 77,
        name: "Sauces",
        info: "Barbecue Sauce",
        image: "https://habanero.in/cdn/shop/products/Spicy-Barbeque-Sauce5_1800x1800.jpg?v=1652280771",
        price: "200/bottle",
    },
    {
        id: 78,
        name: "Cereal",
        info: "Muesli",
        image: "https://rukminim2.flixcart.com/image/750/900/krtjgcw0/cereal-flake/z/s/o/500-muesli-fruit-magic-500-gram-pouch-kellogg-s-original-imag5gy2zcqzvgrs.jpeg?q=20&crop=false",
        price: "200/box",
    },
    {
        id: 79,
        name: "Granola",
        info: "Crunchy Granola",
        image: "https://m.media-amazon.com/images/I/616qK2wgd8L._AC_UF1000,1000_QL80_.jpg",
        price: "150/pack",
    },
    {
        id: 80,
        name: "Seeds",
        info: "Chia Seeds",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDcc0RZteKtA61Ew92OTutx_fV1nmg90LA6w&s",
        price: "60/pack",
    },
    {
        id: 81,
        name: "Seeds",
        info: "Flax Seeds",
        image: "https://www.dryfruitbasket.in/storage/media/38CUtr1jNRwTOsSPjrAC3seQQ05PUiUG49SXo9A3.jpg",
        price: "50/pack",
    },
    {
        id: 82,
        name: "Soup",
        info: "Tomato Soup",
        image: "https://shop.bambinoagro.com/pub/media/catalog/product/cache/64ebcd8fafec312f98a2086a71752804/t/o/tomato-soup-mockup2.png",
        price: "10/pack",
    },
    {
        id: 83,
        name: "Herbs",
        info: "Dried Oregano",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqhxFBYWuZYCoBbUllLseTMqhzdqeGfZrLZk2uLVlSC-9UQ9P5fTefqI8eH8ucEYlsQAk&usqp=CAU",
        price: "50/bottle",
    },
    {
        id: 84,
        name: "Herbs",
        info: "Dried Basil",
        image: "https://m.media-amazon.com/images/I/81Y44-QDFRL.jpg",
        price: "50/bottle",
    },
    {
        id: 85,
        name: "Herbs",
        info: "Parsley",
        image: "https://m.media-amazon.com/images/I/41pWDYAl67L.jpg",
        price: "50/bottle",
    },
    {
        id: 86,
        name: "Honey",
        info: "Wild Honey",
        image: "https://honeyandspice.in/cdn/shop/files/Central_Indian_forests_Wild_Honey-01_17_11zon.jpg?v=1730965622&width=480",
        price: "300/bottle",
    },
    {
        id: 87,
        name: "Herbal Tea",
        info: "Chamomile Tea",
        image: "https://m.media-amazon.com/images/I/71yfmovv3EL.jpg",
        price: "150/box",
    },
    {
        id: 88,
        name: "Herbal Tea",
        info: "Peppermint Tea",
        image: "https://m.media-amazon.com/images/I/71dZLqNppGL.jpg",
        price: "180/box",
    },
    {
        id: 89,
        name: "Energy Drink",
        info: "Electrolyte Drink",
        image: "https://m.media-amazon.com/images/I/61yoMz4N2gL._AC_UF1000,1000_QL80_.jpg",
        price: "50/bottle",
    },
    {
        id: 90,
        name: "Coconut Oil",
        info: "Virgin Coconut Oil",
        image: "https://www.consciousfood.com/cdn/shop/files/1_2.jpg?v=1701757537&width=1445",
        price: "400/bottle",
    },
    {
        id: 91,
        name: "Ghee",
        info: "Organic Ghee",
        image: "https://www.consciousfood.com/cdn/shop/files/1_37.jpg?v=1723529519",
        price: "600/500g",
    },
    {
        id: 1,
        name: "Rice",
        info: "Organic Brown Basmati Rice",
        image: "https://organicmandya.com/cdn/shop/files/Basmathibrownrice_7f666008-539e-46ab-a2b6-96f63de3ce53.jpg?v=1718730849&width=1024",
        price: "90/kg",
    },
    {
        id: 2,
        name: "Pulse",
        info: "Moong Dal",
        image: "https://www.sagarpulses.com/images/pc1.jpg",
        price: "65/kg",
    },
    {
        id: 3,
        name: "Oil",
        info: "Fortune Refined Oil",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-nhYhh2FWidPFeyzGOPuYuLJk-QmwuF2t3w&s",
        price: "160/litre",
    },
    {
        id: 4,
        name: "Sugar",
        info: "Sugar",
        image: "https://media.istockphoto.com/id/1287871932/photo/granulated-white-cane-sugar-in-a-sack-with-a-scoop.jpg?s=612x612&w=0&k=20&c=BTRAQen1dZVsLhOjSZV50mMCyGM1xz9y2nVHCmpWlhg=",
        price: "45/kg",
    },
    {
        id: 94,
        name: "Baking",
        info: "Baking Powder",
        image: "https://rukminim2.flixcart.com/image/850/1000/koenl3k0/baking-ingredient/r/q/u/100-double-acting-baking-powder-baking-powder-bakers-original-imag2v6xh8yew4xg.jpeg?q=90&crop=false",
        price: "40/pack",
    },
    {
        id: 6,
        name: "Toothpaste",
        info: "Toothpaste and Brush",
        image: "https://m.media-amazon.com/images/I/816GTjYsGRL._AC_UF1000,1000_QL80_.jpg",
        price: "820",
    },
    {
        id: 7,
        name: "Cold drinks",
        info: "Sprite, Coca-cola and many more",
        image: "https://5.imimg.com/data5/SELLER/Default/2023/3/296872949/ZZ/GG/BW/77999044/cold-drink-recipe-formulation.jpeg",
        price: "20-100",
    },
    {
        id: 8,
        name: "Broom",
        info: "Grass Broom",
        image: "https://roswp-mediastorage.s3.ap-south-1.amazonaws.com/wp-content/uploads/2023/05/08151154/KING-KONG-Phool-Jhadu-Natural-Assam-Grass.webp",
        price: "120/pack",
    },
    {
        id: 9,
        name: "Detergent",
        info: "Ariel Detergent Powder",
        image: "https://m.media-amazon.com/images/I/81ohM5L2IuL._AC_UF1000,1000_QL80_.jpg",
        price: "180",
    },
    {
        id: 10,
        name: "Rice",
        info: "Brown Rice",
        image: "https://www.bigbasket.com/media/uploads/p/xxl/40091133-6_4-bb-royal-organic-brown-rice.jpg",
        price: "93/kg",
    },
    {
        id: 11,
        name: "Rice",
        info: "Jasmine White Rice",
        image: "https://5.imimg.com/data5/GM/TY/MY-36454470/jasmine-basmati-rice.jpg",
        price: "120/kg",
    },
    {
        id: 12,
        name: "Rice",
        info: "White Mogra Basmati Rice",
        image: "https://5.imimg.com/data5/YK/FC/MY-45373919/mogra-basmati-rice.jpg",
        price: "50/kg",
    },
    {
        id: 13,
        name: "Rice",
        info: "White Rice",
        image: "https://5.imimg.com/data5/SELLER/Default/2021/7/RF/ZN/JD/21732406/jasmine-thai-rice.jpg",
        price: "45/kg",
    },
    {
        id: 14,
        name: "Rice",
        info: "Mehak Indian Basmati Rice",
        image: "https://5.imimg.com/data5/SELLER/Default/2020/9/RS/MR/GX/40887718/indian-basmati-rice-500x500.jpg",
        price: "60/kg",
    },
    {
        id: 15,
        name: "Rice",
        info: "Black Rice",
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/rice/2/r/e/1-black-hv009-black-rice-raw-plastic-bottle-black-rice-havmi-na-original-imagt5yse5gpeeup.jpeg?q=90&crop=false",
        price: "80/kg",
    },
    {
        id: 16,
        name: "Dal",
        info: "Urad Dal",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRfbTepwr3j3Kpz1DPHxnBouYWtDhMmUi2c9AfFIj4kkOODGRRh-sTTfPkkFWne7l5KHzY49mY-DBroITJF4bWc5uoa0JnqwbM5WCcTMWDuYiMatKZE7g6j",
        price: "86/kg",
    },
    {
        id: 17,
        name: "Dal",
        info: "Urad Black Gram Dal",
        image: "https://m.media-amazon.com/images/I/81eUKsofNaL.jpg",
        price: "150/kg",
    },
    {
        id: 18,
        name: "Dal",
        info: "Urad Mogar Dal",
        image: "https://5.imimg.com/data5/CK/QB/MY-2685722/urad-mogar-dal.jpg",
        price: "63/kg",
    },
    {
        id: 19,
        name: "Dal",
        info: "Rajma Chitra Dal",
        image: "https://4.imimg.com/data4/TQ/VF/MY-13307250/rajma-dal-250x250.jpg",
        price: "120/kg",
    },
    {
        id: 20,
        name: "Dal",
        info: "Rajma Dal Kidney Beans",
        image: "https://5.imimg.com/data5/PU/OW/MY-24437295/rajma-dal-500x500.jpg",
        price: "70/kg",
    },
    {
        id: 92,
        name: "Baking",
        info: "Yeast",
        image: "https://rukminim2.flixcart.com/image/850/1000/l071d3k0/baking-ingredient/d/8/r/100-active-instant-dry-yeast-for-baking-bread-cake-donuts-pizza-original-imagcff3upk2uhhe.jpeg?q=90&crop=false",
        price: "50/pack",
    },
    {
        id: 93,
        name: "Baking",
        info: "Vanilla Essence",
        image:"https://m.media-amazon.com/images/I/713PMj-nzNL.jpg",
        price: "100/bottle",
    },
    {
        id: 94,
        name: "Baking",
        info: "Baking Powder",
        image: "https://rukminim2.flixcart.com/image/850/1000/koenl3k0/baking-ingredient/r/q/u/100-double-acting-baking-powder-baking-powder-bakers-original-imag2v6xh8yew4xg.jpeg?q=90&crop=false",
        price: "40/pack",
    },
    {
        id: 95,
        name: "Frozen Desserts",
        info: "Frozen Strawberries",
        image: "https://images-cdn.ubuy.co.in/64c0e382b738330c5f15d419-great-value-whole-strawberries-64-oz.jpg",
        price: "120/pack",
    },
    {
        id: 96,
        name: "Pickles",
        info: "Lemon Pickle",
        image: "https://twobrothersindiashop.com/cdn/shop/files/Lemon_Pickle.jpg?v=1727183467&width=1161",
        price: "90/jar",
    },
    {
        id: 97,
        name: "Snacks",
        info: "Trail Mix",
        image: "https://m.media-amazon.com/images/I/6119NWN0JcL._AC_UF1000,1000_QL80_.jpg",
        price: "400/pack",
    },
    {
        id: 98,
        name: "Snack Bars",
        info: "Granola Bar",
        image: "https://images-cdn.ubuy.co.in/635a406928f4f86e482a3eb9-chocolate-chip-chewy-granola-bars-8ct.jpg",
        price: "20/bar",
    },
    {
        id: 99,
        name: "Chocolates",
        info: "Hazelnut Spread",
        image: "https://m.media-amazon.com/images/I/71NSoXxLUHL._AC_UF1000,1000_QL80_.jpg",
        price: "550/jar",
    },
    {
        id: 100,
        name: "Drinks",
        info: "Lemonade Concentrate",
        image: "https://assets.shop.loblaws.ca/products/20418457003/b1/en/front/20418457003_front_a01_@2.png",
        price: "150/bottle",
    },
    {
        id: 101,
        name: "Drinks",
        info: "Sprite",
        image: "https://www.bigbasket.com/media/uploads/p/xxl/251040-7_2-sprite-soft-drink-lime-flavoured.jpg",
        price: "20-100/bottle",
    },
    {
        id: 102,
        name: "Drinks",
        info: "Coca-Cola",
        image: "https://www.shutterstock.com/image-photo/latvia-riga-05-may-2024-600nw-2462065061.jpg",
        price: "20-100/bottle",
    },
    {
        id: 103,
        name: "Drinks",
        info: "ThumbsUp",
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/aerated-drink/8/a/q/-original-imagsw2afgzcmgmm.jpeg?q=20&crop=false",
        price: "20-100/bottle",
    },
    {
        id: 104,
        name: "Drinks",
        info: "Limka",
        image: "https://m.media-amazon.com/images/I/81utLhkHNHL._AC_UF350,350_QL80_.jpg",
        price: "45/bottle",
    },
    {
        id: 105,
        name: "Drinks",
        info: "Mazza",
        image: "https://m.media-amazon.com/images/I/71sEtarsnVL.jpg",
        price: "60/bottle",
    },
    {
        id: 106,
        name: "Drinks",
        info: "Slice",
        image: "https://purneashop.com/wp-content/uploads/2024/02/purnea-shop-2024-02-17T150656.541.png",
        price: "45/bottle",
    },
    {
        id: 2002,
        name: "Chocolates",
        info: "Caramel Infused",
        image: "https://assets.bonappetit.com/photos/615efa022d33d743fb88668d/1:1/w_2560%2Cc_limit/Caramel-Crunch-Chocolate-Chunklet-Cookies.jpg",
        price: "620/jar",
    },
    {
        id: 2003,
        name: "Chocolates",
        info: "Raspberry Filled",
        image: "https://dash.mediaupdate.co.za/story/image/112608/112608.jpg",
        price: "20/per Chocolate",
    },
    {
        id: 2004,
        name: "Chocolates",
        info: "Crunchy Hazelnut",
        image: "https://th.bing.com/th/id/OIP.xhOYgSw4BpDwgvEi98eP4QHaHa?rs=1&pid=ImgDetMain",
        price: "570/jar",
    },
    {
        id: 2005,
        name: "Chocolates",
        info: "Creamy Milk Chocolate",
        image: "https://th.bing.com/th/id/R.e4c849e84fafb76b129aee66cbe5f239?rik=Ah11cJYyhuRkvA&riu=http%3a%2f%2frukmini1.flixcart.com%2fimage%2f300%2f300%2fl5jxt3k0%2fchocolate%2f6%2fc%2fx%2f900-dairy-milk-melody-milk-chocolate-83-cadbury-original-imagg777aepepawv.jpeg&ehk=sNlQOb2lid8rp5ge8f4uM%2fZ7KyerQEKf2t6xwvoDivM%3d&risl=&pid=ImgRaw&r=0",
        price: "540/jar",
    },
    {
        id: 2006,
        name: "Chocolates",
        info: "Coffee Bean Bits",
        image: "https://th.bing.com/th/id/R.42a000863db0e74200cec016417a90f2?rik=tei6q%2fBlKGMAVQ&riu=http%3a%2f%2fthechocolatewebsite.com%2fwp-content%2fuploads%2f2016%2f02%2fChocolove_Coffee_Crunch_Banner.jpg&ehk=5qGrPzo9ZmVB%2bdfnK2RaMFEnk57xKCIAJUOhrINt0I0%3d&risl=&pid=ImgRaw&r=0",
        price: "600/jar",
    },
];

export default allData;
