import react from "react" 

const Data = [
    {
        id: 5,
        name: "Horlicks",
        info: "Horlicks Lite Regular 1kg",
        image: "https://5.imimg.com/data5/SELLER/Default/2023/4/298033930/IP/GW/YZ/3803435/horlicks-health-nutrition-drink-1-kg-refill-pack.png",
        price: "600/kg",
    },
   
    {
        id:2,
        name:"Pulse",
        info:"Moong Dal",
        image:"https://www.sagarpulses.com/images/pc1.jpg",
        price:"65/kg",
    },
    {
        id:3,
        name:"Refine Oil",
        info:"fortune refine Oil",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-nhYhh2FWidPFeyzGOPuYuLJk-QmwuF2t3w&s",
        price:"160/litre",
    },
    {
        id:4,
        name:"Sugar",
        info:"Sugar",
        image:"https://media.istockphoto.com/id/1287871932/photo/granulated-white-cane-sugar-in-a-sack-with-a-scoop.jpg?s=612x612&w=0&k=20&c=BTRAQen1dZVsLhOjSZV50mMCyGM1xz9y2nVHCmpWlhg=",
        price:"45/kg",
    },
    {
        id:1005,
        name:"Horlicks Milk", 
        info:"Horlicks Lite Regular 1kg Use WIth Milk", 
        image:"https://5.imimg.com/data5/SELLER/Default/2023/4/298033930/IP/GW/YZ/3803435/horlicks-health-nutrition-drink-1-kg-refill-pack.png" , 
        price:"800/kg",
    },
    {
        id:6,
        name:"Toothpaste",
        info:"Toothpaste and Brush" ,
        image:"https://m.media-amazon.com/images/I/816GTjYsGRL._AC_UF1000,1000_QL80_.jpg" ,  
        price:"820",
    },
    {
        id:7,
        name:"Cold drinks",
        info:"Sprite , Coca-cola and many more",
        image:"https://5.imimg.com/data5/SELLER/Default/2023/3/296872949/ZZ/GG/BW/77999044/cold-drink-recipe-formulation.jpeg" ,
        price:"20-100",
    },
    {
        id:8,
        name:"Groom",
        info:"Grass Groom" , 
        image : "https://roswp-mediastorage.s3.ap-south-1.amazonaws.com/wp-content/uploads/2023/05/08151154/KING-KONG-Phool-Jhadu-Natural-Assam-Grass.webp" , 
        price:"120/pack",
    },
    {
        id:9,
        name:"Detergent",
        info:"Ariel Detergent powder",
        image : "https://m.media-amazon.com/images/I/81ohM5L2IuL._AC_UF1000,1000_QL80_.jpg"  , 
        price:"180",
    },
    {
        id: 99,
        name: "Chocolates",
        info: "Hazelnut Spread",
        image: "https://m.media-amazon.com/images/I/71NSoXxLUHL._AC_UF1000,1000_QL80_.jpg",
        price: "550/jar",
    },
    {
        id: 100,
        name: "Drinks",
        info: "Lemonade Concentrate",
        image: "https://assets.shop.loblaws.ca/products/20418457003/b1/en/front/20418457003_front_a01_@2.png",
        price: "150/bottle",
    },
    {
        id: 101,
        name: "Drinks",
        info: "Sprite",
        image: "https://www.bigbasket.com/media/uploads/p/xxl/251040-7_2-sprite-soft-drink-lime-flavoured.jpg",
        price: "20-100/bottle",
    },
    {
        id: 102,
        name: "Drinks",
        info: "Coca-Cola",
        image: "https://www.shutterstock.com/image-photo/latvia-riga-05-may-2024-600nw-2462065061.jpg",
        price: "20-100/bottle",
    },
    {
        id: 103,
        name: "Drinks",
        info: "ThumbsUp",
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/aerated-drink/8/a/q/-original-imagsw2afgzcmgmm.jpeg?q=20&crop=false",
        price: "20-100/bottle",
    },
    {
        id: 104,
        name: "Drinks",
        info: "Limka",
        image: "https://m.media-amazon.com/images/I/81utLhkHNHL._AC_UF350,350_QL80_.jpg",
        price: "45/bottle",
    },
    {
        id: 105,
        name: "Drinks",
        info: "Mazza",
        image: "https://m.media-amazon.com/images/I/71sEtarsnVL.jpg",
        price: "60/bottle",
    },
    {
        id: 106,
        name: "Drinks",
        info: "Slice",
        image: "https://purneashop.com/wp-content/uploads/2024/02/purnea-shop-2024-02-17T150656.541.png",
        price: "45/bottle",
    },
    {
        id: 92,
        name: "Baking",
        info: "Yeast",
        image: "https://rukminim2.flixcart.com/image/850/1000/l071d3k0/baking-ingredient/d/8/r/100-active-instant-dry-yeast-for-baking-bread-cake-donuts-pizza-original-imagcff3upk2uhhe.jpeg?q=90&crop=false",
        price: "50/pack",
    },
    {
        id: 93,
        name: "Baking",
        info: "Vanilla Essence",
        image:"https://m.media-amazon.com/images/I/713PMj-nzNL.jpg",
        price: "100/bottle",
    },
     {
        id:1,
        name:"Rice",
        info:"Organic Brown Basmati Rice",
        image:"https://organicmandya.com/cdn/shop/files/Basmathibrownrice_7f666008-539e-46ab-a2b6-96f63de3ce53.jpg?v=1718730849&width=1024",
        price:"90 per kg",
    },
    {
        id: 89,
        name: "Energy Drink",
        info: "Electrolyte Drink",
        image: "https://m.media-amazon.com/images/I/61yoMz4N2gL._AC_UF1000,1000_QL80_.jpg",
        price: "50/bottle",
    },
    {
        id: 90,
        name: "Coconut Oil",
        info: "Virgin Coconut Oil",
        image: "https://www.consciousfood.com/cdn/shop/files/1_2.jpg?v=1701757537&width=1445",
        price: "400/bottle",
    },
    {
        id: 82,
        name: "Soup",
        info: "Tomato Soup",
        image: "https://shop.bambinoagro.com/pub/media/catalog/product/cache/64ebcd8fafec312f98a2086a71752804/t/o/tomato-soup-mockup2.png",
        price: "10/pack",
    },
   
]

export default Data ; 